### ISSUE TITLE
The way you init variable in check_s3_bucket_policy.py is incorrect

### ISSUE THREAD

**Issue by DamonDeng** [aws/aws-fpga#318]
in `aws-fpga/hdk/common/scripts/check_s3_bucket_policy.py`:

you init the variables like this:

	class PolicyStatement:
	    def __init__(self, statement, principal=None):
	        self.statement = statement
	        self.process_policy_statement(statement, principal)
	        self.principals_re = []
	        self.actions_re = []
	        self.notactions_re = []
	        self.resources_re = []
        

While, you use self.principals_re in the method process_policy_statement, it will cause an error like this:

	AttributeError: PolicyStatement instance has no attribute 'principals_re'

The right sequence should be:

	class PolicyStatement:
	    def __init__(self, statement, principal=None):
	        self.statement = statement
	        self.principals_re = []
	        self.actions_re = []
	        self.notactions_re = []
	        self.resources_re = []

	        self.process_policy_statement(statement, principal)

**Comment by deeppat** [comment]
The PR was merged. Closing the issue.
