### ISSUE TITLE
shell_v04151701 new_cl_template not up to date

### ISSUE THREAD

**Issue by sdoughtymax** [aws/aws-fpga#319]
The 'create_dcp_from_cl.tcl' refers to AWS Design files that no longer exist in the newer shell version.

Example designs using this shell version seem OK though, so can base designs on these for now.

**Comment by AWSwinefred** [comment]
Thanks for pointing out this issue. We will update the create_dcp_from_cl.tcl script.

**Comment by kristopk** [comment]
Resolved in v1.2.1
