### ISSUE TITLE
Syntax error at 1385

### ISSUE THREAD

**Issue by si1242** [aws/aws-fpga#326]
I'm trying to execute this python script, but this error occured.  

>Traceback (most recent call last):
  File "./check_s3_bucket_policy.py", line 1385, in <module>
    logger.debug("{0} inline policy: {1}".format(policy_name))
IndexError: tuple index out of range

I guess the first argument of format() was removed by mistake.
The correct code is as follows, right?
```
logger.debug("{0} inline policy: {1}".format(group_name, policy_name))
```

**Comment by AWSwinefred** [comment]
Thank you for pointing out the syntax error. Our development team will look at it immediately.
