### ISSUE TITLE
fatal error: xcldma/include/xdma-ioctl.h: No such file or directory

### ISSUE THREAD

**Issue by yongchaodeng** [aws/aws-fpga#339]
fatal error: xcldma/include/xdma-ioctl.h: No such file or directory
 fatal error: baremetal/mgmt/mgmt-ioctl.h: No such file or directory
when I run makefile in sdk/SDAccel/userspace/src,the report is fatal error,
I could not find these files in github.

**Comment by kristopk** [comment]
SDAccel is not currently supported
