### ISSUE TITLE
error in check_s3_bucket_policy.py

### ISSUE THREAD

**Issue by ZaharAd** [aws/aws-fpga#350]
I try to run this script check_s3_bucket_policy.

> check_s3_bucket_policy.py --dcp-bucket zahar-fpga --dcp-key dcp-hello-world/17_08_01-095118.Developer_CL.tar --logs-bucket zahar-fpga --logs-key logs-folder

to verify the bucket policy and get this error: 

>  File "check_s3_bucket_policy.py", line 1440, in <module>
    num_errors += checker.check()
  File "check_s3_bucket_policy.py", line 344, in check
    self.check_user_policy()
  File "check_s3_bucket_policy.py", line 293, in check_user_policy
    statement = PolicyStatement(statement, self.user_account_arn)
  File "check_s3_bucket_policy.py", line 53, in __init__
    self.process_policy_statement(statement, principal)
  File "check_s3_bucket_policy.py", line 83, in process_policy_statement
    actions = statement['Action']
TypeError: string indices must be integers

I use the example policy with changes at folder and file names .
any idea what can make it?

**Comment by AWSwinefred** [comment]
This was answered in the AWS FPGA forum. Below is a copy:

Hi Zahar,

I mentioned this in another thread just now too.

This error seems to stem from a bug in the 'check_s3_bucket_policy' helper script. This is just a helper script to see if your bucket policy is correct so we can access the dcp from the S3 location.

While we triage and try fixing the bug in this helper script, this should not prevent you from calling the next step to create an fpga image:
$ aws ec2 create-fpga-image \
--name <afi-name> \
--description <afi-description> \
--input-storage-location Bucket=<dcp-bucket-name>,Key=<path-to-tarball> \
--logs-storage-location Bucket=<logs-bucket-name>,Key=<path-to-logs> \
https://forums.aws.amazon.com/ \
--no-dry-run

Let me know if that doesn't work.

Thanks,

Deep
