### ISSUE TITLE
In READMEs with examples consider using linkable headings instead of bullets

### ISSUE THREAD

**Issue by dutchalthoff** [aws/aws-fpga#371]
I found that linking to a doc page is sometimes not specific enough. Instead, I need to link to the exact example snippet.

Currently, the bullets are used. Switching to headings would provide anchors that can be linked.

For example on [this page](https://github.com/aws/aws-fpga/blob/master/hdk/docs/fpga_image_attributes.md#example-usage):

- Make AFI public:
```
    $ aws ec2 --region us-east-1 modify-fpga-image-attribute --fpga-image-id afi-0e5361a69d2af203d --operation-type add --user-groups all
<...>
```
to 
#### Make AFI public:
```
    $ aws ec2 --region us-east-1 modify-fpga-image-attribute --fpga-image-id afi-0e5361a69d2af203d --operation-type add --user-groups all
<...>
```

**Comment by kristopk** [comment]
Hi,  As we improve the documentation we will replace bullets with anchors that can be linked.
