### ISSUE TITLE
How can I get the reports after running on F1

### ISSUE THREAD

**Issue by AlverLyu** [aws/aws-fpga#393]
After running the hardware emulation of the Xilinx example helloworld_ocl with  $AWS_PLARTFORM_4DDR_DEBUG, it would generates the profile reports. While after running in the FPGA, there's no reports generated. I have tried to modify the makefile `rules.mk` to add a `--debug` option for `xocc`, which does not help. How can I get these reports for the hardware running?

**Comment by ThomasXilinx** [comment]
By default, reporting is:
- Enabled for the emulation flows
- Disabled when running on the FPGA

To enable reporting when running on the FPGA, create a file called sdaccel.ini in the run directory with the following content:

> [Debug]
>  timeline_trace=true
>  profile=true

The content of the sdaccel.ini file control which reports get generated during both emulation and FPGA runs.

**Comment by AlverLyu** [comment]
@ThomasXilinx This exactly solved my problem. Thank you very much.
