### ISSUE TITLE
Hardware Emulation but hardware fails

### ISSUE THREAD

**Issue by gsneha26** [aws/aws-fpga#416]
Mu custom RTL in the system created using the SDAccel RTL Kernel Wizard 2017.1 works correctly in the hardware emulation mode. But when I run on the AWS F1 instance, the program hangs up as soon as the input is sent to the FPGA (no response back).

Any input on what could be the potential issue?

**Comment by kristopk** [comment]
Since you are requesting help, please use the AWS forum for support questions:
https://forums.aws.amazon.com/forum.jspa?forumID=243
