### ISSUE TITLE
Create_Runtime_AMI.md is broken

### ISSUE THREAD

**Issue by vitesse-ftian** [aws/aws-fpga#418]
Any issues related to HDK or SDK should be filed on FPGA development Forum.

The [AWS FPGA Development User Forum](https://forums.aws.amazon.com/forum.jspa?forumID=243) is the first place to go to post questions, suggestions and important announcements. 

Section 2,  Copy required Xilinx SDAccel Runtime Libraries to the Instance and Reboot your Runtime Instance.

The instruction is broken, first, it should be $XILINX_SDX, not $XIILNX_SDX.   Second, those binary files to be copied have be moved around in the newest developer AMI. 

Maybe just ask people to copy the rte.dyn directory?

**Comment by vitesse-ftian** [comment]
On ubuntu, I have to do the following in addition to the instruction,

1. XILINX_SDX directory must be named as 2017.4.XXX, because the sdaccel_setup.sh uses first 6 char as release version,
2. Must copy lib/lnx64.0/Ubuntu directory as well.

After these steps seems the ubuntu f1 instance is working.  I can run helloworld.

**Comment by AWScsaralay** [comment]
Hello,

Thank you for bringing this to our notice. The paths have changed in the 2017.4. We will update our documentation.

Thanks,
AWSChakra

**Comment by AWSaalluri** [comment]
This has been fixed in Developer Kit release 1.4.6. Instruction should work for both 2017.4 & 2018.3.

https://github.com/aws/aws-fpga/blob/master/SDAccel/docs/Create_Runtime_AMI.md

Thanks,
AWSaalluri
