### ISSUE TITLE
Why S3 bucket and its related things are required for awsxclbin

### ISSUE THREAD

**Issue by adki** [aws/aws-fpga#422]
I wonder why S3 things are required to prepare awsxclbin.

When I try to prepare awsxclbin from xclbin using create_sdaccel_afi.sh, it requires s3_bucket, s3_dcps_key, s3_log_key and so.

These are not explained in this README file.

Above all, why ASW F1 doe not use something automatic conversion internally when xclbin file is given for SDAccel/OpenCL application runs?

AWS F1 instance for SDAccel requires too many additional prerequisites, which are not common at local machine.

Any help could make me save time and money and efforts.

**Comment by kristopk** [comment]
Hi, 
Please post questions to the AWS forum:
https://forums.aws.amazon.com/forum.jspa?forumID=243
Thanks!
