### ISSUE TITLE
xdma driver install failed

### ISSUE THREAD

**Issue by forcici** [aws/aws-fpga#429]
I've encountered a problem when installing xdma driver, the error said:

> **Can't read private key**

and

> **modprobe: ERROR: could not insert 'xdma': Exec format error**

as you can see in the following logs

I've also tried the command:

> **lsmod | grep xdma**

and see nothing.

Could anyone help me to checkout the problem?  Thanks!

here are the logs:

> $ sudo make install all
> Makefile:25: XVC_FLAGS: .
> make -C /lib/modules/3.10.0-693.21.1.el7.x86_64/build M=/home/centos/aws-fpga/sdk/linux_kernel_drivers/xdma modules
> make[1]: Entering directory `/usr/src/kernels/3.10.0-693.21.1.el7.x86_64'
> /home/centos/aws-fpga/sdk/linux_kernel_drivers/xdma/Makefile:25: XVC_FLAGS: .
>   Building modules, stage 2.
> /home/centos/aws-fpga/sdk/linux_kernel_drivers/xdma/Makefile:25: XVC_FLAGS: .
>   MODPOST 1 modules
> make[1]: Leaving directory `/usr/src/kernels/3.10.0-693.21.1.el7.x86_64'
> make -C /lib/modules/3.10.0-693.21.1.el7.x86_64/build M=/home/centos/aws-fpga/sdk/linux_kernel_drivers/xdma modules_install
> make[1]: Entering directory `/usr/src/kernels/3.10.0-693.21.1.el7.x86_64'
>   INSTALL /home/centos/aws-fpga/sdk/linux_kernel_drivers/xdma/xdma.ko
> Can't read private key
>   DEPMOD  3.10.0-693.21.1.el7.x86_64
> make[1]: Leaving directory `/usr/src/kernels/3.10.0-693.21.1.el7.x86_64'
> depmod -a
> install -m 644 10-xdma.rules /etc/udev/rules.d
> rmmod -s xdma || true
> modprobe xdma
> modprobe: ERROR: could not insert 'xdma': Exec format error
> make: [install] Error 1 (ignored)
> make: `all' is up to date.
>

**Comment by forcici** [comment]
Thanks for replying so fast
I've removed xocl driver, and install the xdma driver again, but one of the error still exists 

> Can't read private key

I use

> lsmod | grep xdma

and I can see xdma modules
But when I checked the /dev/ directory,  I still cannot find  device like  "xdmaX_h2c_Y"
It seems xdma driver is not successfully installed.
Could you help me to check out ?
Thank you!

The following are logs
> [centos@xdma]$ sudo make install all
> Makefile:25: XVC_FLAGS: .
> make -C /lib/modules/3.10.0-693.21.1.el7.x86_64/build M=/home/centos/aws-fpga/sdk/linux_kernel_drivers/xdma modules
> make[1]: Entering directory `/usr/src/kernels/3.10.0-693.21.1.el7.x86_64'
> /home/centos/aws-fpga/sdk/linux_kernel_drivers/xdma/Makefile:25: XVC_FLAGS: .
>   Building modules, stage 2.
> /home/centos/aws-fpga/sdk/linux_kernel_drivers/xdma/Makefile:25: XVC_FLAGS: .
>   MODPOST 1 modules
> make[1]: Leaving directory `/usr/src/kernels/3.10.0-693.21.1.el7.x86_64'
> make -C /lib/modules/3.10.0-693.21.1.el7.x86_64/build M=/home/centos/aws-fpga/sdk/linux_kernel_drivers/xdma modules_install
> make[1]: Entering directory `/usr/src/kernels/3.10.0-693.21.1.el7.x86_64'
>   INSTALL /home/centos/aws-fpga/sdk/linux_kernel_drivers/xdma/xdma.ko
> Can't read private key
>   DEPMOD  3.10.0-693.21.1.el7.x86_64
> make[1]: Leaving directory `/usr/src/kernels/3.10.0-693.21.1.el7.x86_64'
> depmod -a
> install -m 644 10-xdma.rules /etc/udev/rules.d
> rmmod -s xdma || true
> modprobe xdma
> make: `all' is up to date.
>

**Comment by deeppat** [comment]
Hi forcici,

This is not really an error that should stop the installation.
> Can't read private key

Can you try clearing the fpga slot first by calling:

```
sudo fpga-clear-local-image -S0
AFI          0       none                    cleared           1        ok               0       0x071417d3
AFIDEVICE    0       0x1d0f      0x1042      0000:00:1d.0
```

After that if you run sudo make install, it should bind the driver to the cleared AFI.

Make sure that you run the following in case you've installed any of these drivers before: 
> sudo rmmod edma_drv
> sudo rmmod xocl

Let us know here if this doesn't help! 

Thanks,

Deep

**Comment by forcici** [comment]
Thanks for you response.
I tried what you told me to do, and then I reboot AWS cloud service. Now I am able to find xdma device in directory /dev/*
Thank you !
