### ISSUE TITLE
Error starting instances

### ISSUE THREAD

**Issue by QueSSence** [aws/aws-fpga#485]
![IMG-20200417-WA0022](https://user-images.githubusercontent.com/43127749/79560509-58814180-80c5-11ea-99ff-19d907ca64bb.jpg)

**Comment by deeppat** [comment]
@QueSSence: Depending on customer usage in a specific AZ or region, one can see such errors. Please look at the [EC2 troubleshooting guide](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/troubleshooting-launch.html#troubleshooting-launch-capacity) as it explains next steps.

**Comment by QueSSence** [comment]
Hi Deeppat, Now I am getting a different error, we generating a bit file within specified limits
![aws-fpga_error](https://user-images.githubusercontent.com/43127749/79679744-57b3f100-8226-11ea-8c77-f33b2a7a179b.PNG)

**Comment by rakesh-ceremorphic** [comment]
I am trying to launch f1.2xLarge instance.But getting above errors.I checked the documentation page.This configuration is supported..Please let me know what could be the issue.

**Comment by deeppat** [comment]
Hi @rakesh-ceremorphic @QueSSence , I think you'd be better served if you start a support ticket with AWS. We are here to help you out with the Developer Kit and I feel like AWS Support would be much better equipped to help you out with EC2 issues like this. Please let us know if you have further questions that we can help with!

**Comment by deeppat** [comment]
Closing as I am assume this problem is resolved. Please re-open if this is still an issue!
