### ISSUE TITLE
Running Hardware development kit in AWS FPGA development and s3 bucket creation

### ISSUE THREAD

**Issue by SSandeep19** [aws/aws-fpga#542]
Hi,
I am running hardware development kit in FPGA development instance. I want to know if I should run the development kit as a root user or as a IAM user ?. While creating s3 bucket I am not able to create while I am doing it as a root user. If I have to switch to IAM user while creating s3 bucket from root user how do I do it ? Thank you for any help.

Regards,
Sandeep

**Comment by kyyalama2** [comment]
Hi Sandeep

Very sorry for the delayed response. Just checking if you still need help with this or if this issue was resolved

Thanks

**Comment by kyyalama2** [comment]
closing the issue. Please feel free to reopen if required
