### ISSUE TITLE
can't find xilinx_aws-vu9p-f1-04261818_dynamic_5_0.dsa file in aws_platform

### ISSUE THREAD

**Issue by umairqaisar000** [aws/aws-fpga#543]
Please I can't find xilinx_aws-vu9p-f1-04261818_dynamic_5_0.dsa file or any hw folder in aws_platform, please upload it as I can't load custom project on sdaccel.

**Comment by AWScsaralay** [comment]
Hello,

Were you able to run example designs posted on github?
https://github.com/aws/aws-fpga/blob/master/SDAccel/examples/aws/helloworld_ocl_runtime/README.md#exclamation-please-note-xclbin--awsxclbin-file-formats-have-changed-from-sdx-20183-onwards-xclbin--awsxclbin-files-generated-using-earlier-sdx-versions-are-not-compatible-with-2018320191-based-xrts-if-you-are-using-a-2018320191-based-xrt-please-copy-over-awsxclbin--helloworld-executable-files-provided-in-the-20183_20191-subdirectory-to-this-folder

Could you also specif which tool version are you using? 

thanks!
Chakra

**Comment by umairqaisar000** [comment]
I am using SDx 2018.3

**Comment by AWScsaralay** [comment]
All the required files are downloaded during initial setup script. If not done already, could you please try running initial setup as described in the link below?
https://github.com/aws/aws-fpga/tree/master/SDAccel#github-and-environment-setup

**Comment by umairqaisar000** [comment]
Okay Thank you will try and see if it works.

**Comment by kyyalama2** [comment]
closing issue. Please feel free to reopen if required
