### ISSUE TITLE
links to XRT 2021.2 rpms are not available on XRT_installation_instructions.md

### ISSUE THREAD

**Issue by xlz-jbleclere** [aws/aws-fpga#550]
Hi, 
As the AMI v1.12 supporting Vivado 2021.2 has been recently released, I'm expecting to see the XRT 2021.2 RPMs also available on the usual page: https://github.com/aws/aws-fpga/blob/master/Vitis/docs/XRT_installation_instructions.md
But it stops at 2021.1. 
Could you please update the page with the links?
Regards

**Comment by czfpga** [comment]
Hi,

Thank you for reaching out for the XRT 2021.2 release. Let me bring this up to the dev team. I'll keep you posted. 

Thanks,

Chen

**Comment by czfpga** [comment]
Hi,

Please see the updated link (https://github.com/aws/aws-fpga/blob/master/Vitis/docs/XRT_installation_instructions.md) for the XRT 2021.2 RPMs. 

Thanks,

Chen

**Comment by xlz-jbleclere** [comment]
Hi Chen, Thanks for the update but the RPM links in the AL2 column seems to target the 2022.1 not the 2021.2. Do you confirm?

**Comment by czfpga** [comment]
Hi JB,

I've confirmed with the team that this the latest 2021.2 release. Please let me know if you found an problem using it. Thanks.

Chen

**Comment by czfpga** [comment]
Hi JB,

Are you able to confirm the version for the latest 2021.2 RPM release? I'll go ahead close this issue if you have no further questions. Please let me know. Thanks.

Chen

**Comment by kyyalama2** [comment]
Hi JB,

Just checking if you still need help with this issue

Thanks

**Comment by kyyalama2** [comment]
closing issue
