### ISSUE TITLE
peer2peer DMA

### ISSUE THREAD

**Issue by abhaypelago** [aws/aws-fpga#553]
We are not able to perform peer2peer DMA. We do see BAR4 addresses.

bar[0] start: 0x84000000 size: 0x2000000
bar[1] start: 0x83a00000 size: 0x200000
bar[2] start: 0x5e000410000 size: 0x10000
bar[4] start: 0x5c000000000 size: 0x2000000000

Driver is able to do MMIO operation to BAR4 space to both FPGAs. Which we can see happening on PCIS bus via ILA.
We program 0x5c000000000 to FPGA1 which tries to read to read from FPGA2. We do not see any access coming to PCIS on this FPGA2.
There are no AXI errors reported on FPGA1 and DMA completes. So, our guess is PCIe bridge is routing those 0x5c000000000 from FPGA1 to host instead of sending them to FPGA2. Are there any leading (MSB) address bits we need to set?
Or are there any other steps to perform?

**Comment by AWScsaralay** [comment]
Hello,

Could you please check if BusMaster+ is set in FPGA1 and Mem+ is set in FPGA2's PCIe config space? 

For example: 
```
[$] lspci -v -s 0000:00:0f.0
00:0f.0 Memory controller: Device 1d0f:f001
       Subsystem: Device fedc:1d51
       Physical Slot: 15
       Control: I/O- Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx-
       Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
       Latency: 0
       Region 0: Memory at c4000000 (32-bit, non-prefetchable) [size=32M]
       Region 1: Memory at c6000000 (32-bit, non-prefetchable) [size=2M]
       Region 2: Memory at 5e000410000 (64-bit, prefetchable) [size=64K]
       Region 4: Memory at 5c000000000 (64-bit, prefetchable) [size=128G]
```

Could you also share `metrics` dump from both the FPGAs?
https://github.com/aws/aws-fpga/blob/master/hdk/docs/HOWTO_detect_shell_timeout.md#how-to-detect-a-shell-timeout-has-occurred

Also, please refer to the link below for additional details on Peer2Peer: 
https://github.com/awslabs/aws-fpga-app-notes/blob/master/Using-PCIe-Peer2Peer/README.md

Please let us know if you still run into these issues. We will be happy to help. 

Thanks!
Chakra

**Comment by kyyalama2** [comment]
customer followed up on email thread. Resolved
