### ISSUE TITLE
Unable to run FPGA dev AMI on r6 and c6 instances

### ISSUE THREAD

**Issue by kenta2** [aws/aws-fpga#574]
This is a continuation of https://github.com/aws/aws-fpga/issues/571 . @kyyalama2 said there to reopen that ticket if I saw further issues, but I am unable to reopen a closed ticket.  Although I confirm that the FPGA Dev AMI now works for m6i, I am also interested in r6i and r6a (more memory).  Can you please enable the r6 family as well?

You will probably have other customers interested in the c6 family, too.

**Comment by kyyalama2** [comment]
Dear customer
The FPGA dev AMI is now supported on r6 and c6 instances. Please feel free to try the dev AMI and let us know if you need any additional help or if you have any comments/feedback

Thanks
