### ISSUE TITLE
What is xdma0_user mapped to?

### ISSUE THREAD

**Issue by Quarky93** [aws/aws-fpga#577]
Hi, I was under the assumption that xdma0_user would be mapped to one of the AXI-Lite interfaces similar to the standard Xilinx IP. However after some testing, I'm left confused. Can someone let me know is xdma0_user mapped to the sda, ocl, or bar1 axi-lite buses? Or must I use the AWS API? I would prefer to use xdma0_user to keep compatibility with on-prem cards using XDMA.

**Comment by kyyalama2** [comment]
Dear customer

Thank you for your interest in AWS. The AWS FPGA PCIe Memory map is available at 
https://github.com/aws/aws-fpga/blob/master/hdk/docs/AWS_Fpga_Pcie_Memory_Map.md#aws-fpga-pcie-memory-map

Please refer to the table here for information on mapping of PF/BAR address spaces. Please let us know if this is helpful or if you are looking for any additional information that can help with your debug

Thanks

**Comment by Quarky93** [comment]
Hi, I'm aware of the BAR mapping. However I'm less certain on what the xdma driver actually maps to on the xdma0_user character device specifically.

Normally with on-prem FPGA with XDMA, the xdma0_user is mapped to the AXI-Lite bus. I'm not sure what it does on AWS F1.

**Comment by Quarky93** [comment]
Ok, xdma0_user is mapped to OCL :) .
@kyyalama2 should this be documented?
