### ISSUE TITLE
Unable to simulate hello world HLx in vivado

### ISSUE THREAD

**Issue by johnrabo** [aws/aws-fpga#590]
I'm having the exact same problem as an issue that was already closed (but I didn't see any resolution).

https://github.com/aws/aws-fpga/issues/551

Any thoughts on how to resolve this?

**Comment by johnrabo** [comment]
I changed --additional_option to --gcc_compile_option  
aws-fpga/hdk/common/shell_v04261818/hlx/verif/scripts/dpi_xsim.tcl

And it now works.

**Comment by kyyalama2** [comment]
Dear customer, 
Thanks for the update. Can you please confirm if this issue can be closed

Thanks
Kishore

**Comment by johnrabo** [comment]
Yes that fixes the problem and can be closed. However does this fix need to go in as a PR?
