### ISSUE TITLE
[Question]: Multi beat burst transactions between two FPGAs

### ISSUE THREAD

**Issue by sajjadahmed677** [aws/aws-fpga#605]
Hi all,

I have a questions regarding burst transactions between two FPGAs. Is it supported? if yes can anyone please refer any example which could be used as reference.

Thanks,

**Comment by czfpga** [comment]
Hi,

Please refer to our Peer-2-Peer document (https://github.com/awslabs/aws-fpga-app-notes/blob/master/Using-PCIe-Peer2Peer/README.md) for example and detailed instructions on enabling data exchange between FPGAs. Please carefully review the restrictions listed in that document. For burst transaction, as long as the transaction is fully compliant to the AXI standard, it is supported. I hope this answers your question.

Thanks,

Chen

**Comment by kyyalama2** [comment]
Dear customer, 
Just checking if you need have any further questions on the issue or if we can close the request

Thanks
