### ISSUE TITLE
Question: Availability zones and instance availability factor

### ISSUE THREAD

**Issue by ljp0101** [aws/aws-fpga#608]
I'm occasionally running into not being able to pick up spot f1.2xl instances in us-east-1. My VPC is configured to use availability zones 1-3. Will it increase instance availability factor if I change the VPC to encompass all availability zones? Understand I can also request larger instances and/or make capacity reservations but not ready to do these optimizations yet.

**Comment by kyyalama2** [comment]
Dear customer
closing the ticket, since no follow up question/request on this issue. Please feel free to re-open if you need further help. Thank you so much for your interest in F1 instances and contacting AWS
