### ISSUE TITLE
Can an AFI support on the fly partial reconfiguration through providing AWS multiple DCPs or a partially reconfigurable DCP?

### ISSUE THREAD

**Issue by hgrove** [aws/aws-fpga#609]
The goal is to have an FPGA in an F1 instance that can be partially reconfigured on the fly to support a variety of use cases. Could this be done through providing AWS a DCP that in itself partially reconfigurable so that the AFI produced can be partially reconfigured on the fly? Or perhaps could the developer provide multiple DCPs that could be loaded compiled onto the AFI and be loaded on the fly?

**Comment by AWScsaralay** [comment]
Hello, thanks for reaching out to AWS with your question. 

F1 does not support multiple partially reconfigurable design/bitstreams to be loaded into the FPGA. Every AFI created from Customer DCP must adhere to the [aws-shell-interface-specification](https://github.com/aws/aws-fpga/blob/master/hdk/docs/AWS_Shell_Interface_Specification.md#aws-shell-interface-specification). 

However, AWS allows customers to dynamically switch between multiple AFIs on the same instance. i.e., A customer can load AFI-A on an instance, run the application, and then load AFI-B to continue with the remainder of application. Please note that both AFI-A and AFI-B should be generated as two separate designs.

Please let us know if you need any further details or have any questions. 

Thanks!
Chakra

**Comment by hgrove** [comment]
Thank you for this information.

What is an approximate AFI load time?

From: AWScsaralay ***@***.***>
Sent: Thursday, May 25, 2023 12:02 PM
To: aws/aws-fpga ***@***.***>
Cc: Grove, Haily ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [aws/aws-fpga] Can an AFI support on the fly partial reconfiguration through providing AWS multiple DCPs or a partially reconfigurable DCP? (Issue #609)

Hello, thanks for reaching out to AWS with your question. F1 does not support multiple partially reconfigurable design/bitstreams to be loaded into the FPGA. Every AFI created from Customer DCP must adhere to the aws-shell-interface-specification. 


Hello, thanks for reaching out to AWS with your question.

F1 does not support multiple partially reconfigurable design/bitstreams to be loaded into the FPGA. Every AFI created from Customer DCP must adhere to the aws-shell-interface-specification<https://urldefense.com/v3/__https:/github.com/aws/aws-fpga/blob/master/hdk/docs/AWS_Shell_Interface_Specification.md*aws-shell-interface-specification__;Iw!!NiYMbFKv!PXHjn2zrTTyjvvjq-I_6tgsuF5EiWIYbKuL3L8sMM6zaHJDiX7wIDNvMIkMjuI2eYmSglPLL7xDpZMsEH66FHn5-hg8$>.

However, AWS allows customers to dynamically switch between multiple AFIs on the same instance. i.e., A customer can load AFI-A on an instance, run the application, and then load AFI-B to continue with the remainder of application. Please note that both AFI-A and AFI-B should be generated as two separate designs.

Please let us know if you need any further details or have any questions.

Thanks!
Chakra

**Comment by AWScsaralay** [comment]
Hi, the AFI load time varies due to multiple factors, however AWS internally caches recently used AFIs by same customers to reduce AFI load times. Please see the doc below for details: 
https://github.com/aws/aws-fpga/blob/master/hdk/docs/load_times.md

Please reach out to us if you have any questions. 

Thanks!
Chakra
