### ISSUE TITLE
DMA read is not correct

### ISSUE THREAD

**Issue by Gogul-N** [aws/aws-fpga#627]
Hi,

I was trying to read a memory from FPGA using DMA read and I got the following output. a4, e, 25, 3c, 28, 85, dc, 5, **a4, e, 25, 3c, 28, 85, dc, 5.**

8 bytes are repeated here. The expected output is a4, e, 25, 3c, 28, 85, dc, 5, **e6, 57, 45, 88, 9d, 73, a5, a7**.

I have to read twice to get the proper output. If I read the entire memory using PCIe, I am getting the correct data. What is the cause of this problem.?

Even while using PCIe, I am facing this problem sometimes. So that I have to read twice to overcome this. But due to timing constraint I have to read only once.

Kindly help me.

Thank you.

**Comment by czfpga** [comment]
This is duplicated to this thread: https://repost.aws/questions/QUvqq7GcdQTvWMDwqs2WkWLA#ANPzs2mYd1S461myfbd3S5CA
