### ISSUE TITLE
Encounter error when using dcp to create AFI image

### ISSUE THREAD

**Issue by zackyen53614** [aws/aws-fpga#655]
After reading this repo, I realize that the first half of steps are about to create dcp file by source code, and then use dcp to create AFI. However, my situation is that I got a dcp file directly from design, I think maybe I can skip the steps for dcp compiling, and use my dcp to create AFI directly by the command in this repo, but I got error, just like below:

ERROR: [Project 1-589] Checkpoint part 'xcu200-fsgd2104-2-e' is not available. Closest-matching available part(s): xcvu9p-fsgd2104-1-e, xcvu9p-fsgd2104-1-i, xcvu9p-fsgd2104-2-e, xcvu9p-fsgd2104-2-i, xcvu9p-fsgd2104-2L-e, xcvu9p-fsgd2104-2LV-e, xcvu9p-fsgd2104-3-e

Because looking that the error may be related to au200 board part connection inavailable, first try is to place au200 board file under the vivado path, which is the environment for create AFI, but still encounter same error after retrying. Accordingly, I want to know whether there is another method or step to resolve the problem, or maybe which path should I place my au200 board file would be proper 

By the way, I also run the hello_world example in this repo, and found that dcp file would be compiled into a tar file with manifest.txt, and we use the tar file to create AFI, so I also create a manifest.txt, and modify the cell name and hash in manifest.txt, and also compile my dcp and manifest to tar file and run creating AFI, but it's obvious that I got the error mentioned above, so I also want to check whether the action of create manifest.txt and compile them into tar manually is proper or not

thank you!

Zack Yen
Student

**Comment by czfpga** [comment]
Hi Zack,

It seems that your design was created for an U200 card not for F1. AFI cannot be created for non-F1 card. Please refer to this repo https://github.com/aws/aws-fpga-f1-u200 on how to migrate your design to F1. Hope that helps.

In addition, the issu (https://github.com/aws/aws-fpga/issues/654) seems duplicated to this. Please close it if you no longer need that issue. Thanks.

Chen
